id: 3fac95879d354f26910be37daecbad11
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_563-Upholding_the_Great_Secret_Mantra-v1
  language: bo
  author: ''
  volume: {}
